version: 2
jobs:
  build_dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install"
      - run:
          name: Run react build
          command: "sudo REACT_APP_APIENDPOINT=https://hgn-rest-dev.herokuapp.com/api REACT_APP_SENTRY_URL=$SENTRY_URL_DEV npm run build"
      - run:
          name: Deploy app
          command: ./node_modules/.bin/surge build --domain $SURGE_DOMAIN_DEV

  build_PROD:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install"
      - run:
          name: Run react build
          command: "sudo REACT_APP_APIENDPOINT=$APIENDPOINT_PROD REACT_APP_SENTRY_URL=$SENTRY_URL_PROD npm run build"
      - run:
          name: Deploy app
          command: ./node_modules/.bin/surge build --domain $SURGE_DOMAIN_PROD

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only: development
      - build_PROD:
          filters:
            branches:
              only: master
