version: 2
jobs:
  build_dev:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: npm install
          command: "sudo npm install"
      - run:
          name: Run react build
          command: "sudo REACT_APP_APIENDPOINT=$APIENDPOINT_DEV REACT_APP_SENTRY_URL=$SENTRY_URL_DEV npm run build"
      - run:
          name: Deploy app
          command: ./node_modules/.bin/surge build --domain $SURGE_DOMAIN_DEV

  build_beta:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: npm install
          command: "sudo npm install"
      - run:
          name: Run react build
          command: "sudo REACT_APP_APIENDPOINT=$APIENDPOINT_BETA SKIP_PREFLIGHT_CHECK=true npm run build"
      - run:
          name: Deploy app
          command: ./node_modules/.bin/surge build --domain $SURGE_DOMAIN_BETA

  build_PROD:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: npm install
          command: "sudo npm install"
      - run:
          name: Run react build
          command: "sudo REACT_APP_APIENDPOINT=$APIENDPOINT_PROD REACT_APP_SENTRY_URL=$SENTRY_URL_PROD npm run build"
      - run:
          name: Deploy app
          command: ./node_modules/.bin/surge build --domain $SURGE_DOMAIN_PROD

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - development
                - fixing_bugs
      - build_beta:
          filters:
            branches:
              only:
                - development
                - deploy_beta
                - fixing_bugs
      - build_PROD:
          filters:
            branches:
              only: master
