name: Build and Cache Highest Good App
on:
  push:
    branches:
      - main
      - development
jobs:
  build:
    name: Build and Cache / ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      # We don't run tests here since we assume it's already done during PR process.
      - name: Update Browser List
        run: bunx browserslist@latest --update-db
      - name: Build React App
        run: yarn build
        env:
          NODE_ENV: ${{ github.ref_name == 'main' && 'production' || 'development' }}
          REACT_APP_APIENDPOINT: ${{ env.REACT_APP_API_ENDPOINT }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build
